# Cars Category

In [83]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
# from bs4 import BeautifulSoup
# import requests
import pandas as pd

In [84]:
locations = []
add_dates = []
prices = []
makes = []
models = []
model_years = []
gears = []
fuel_types = []
engine_ccs = []
mileage_km = []

In [85]:
def get_cars(from_page, to_page):
    driver = webdriver.Chrome(executable_path='C:\selenium_browser_drivers\chromedriver.exe')

    for num in range(from_page,to_page):

        url = 'https://www.patpat.lk/vehicle/car?page='+str(num)

        print('Started Page no.'+str(num)+'. - ', url)

        if num == 593:
            print("PLEASE NOTE - You have reached the last page. If I'm gonna throw an error on this page, ignore me and run the rest of the code as last page may not contain 60 elements. If not, don't worry about what I said..")

        time.sleep(2)
        driver.get(url)

        driver.implicitly_wait(5)

        for i in range(1,11):

            path = "//*[@id='app']/div[2]/section[4]/div[2]/div/div["+ str(i)+ "]/div/div[1]/a/img"
            driver.find_element_by_xpath(path).click()
    
            try:
                location = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/p").text
                locations.append(location)

                add_date = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/p").text
                add_dates.append(add_date)

                price = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/div[2]/div[1]/div[1]/strong").text
                prices.append(price)

                make = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/div[2]/div[1]/table/tbody/tr[5]/td[2]").text
                makes.append(make)

                model = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/div[2]/div[1]/table/tbody/tr[6]/td[2]").text
                models.append(model)

                model_year = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/div[2]/div[1]/table/tbody/tr[2]/td[2]").text
                model_years.append(model_year)

                gear = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/div[2]/div[1]/table/tbody/tr[4]/td[2]").text
                gears.append(gear)

                fuel_type = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/div[2]/div[1]/table/tbody/tr[7]/td[2]").text
                fuel_types.append(fuel_type)

                engine_cc = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/div[2]/div[1]/table/tbody/tr[8]/td[2]").text
                engine_ccs.append(engine_cc)

                mileage = driver.find_element_by_xpath("//*[@id='app']/div[2]/div[1]/div[2]/div[1]/table/tbody/tr[9]/td[2]").text
                mileage_km.append(mileage)

            except Exception as e:
                print(e)
            driver.back()
    driver.quit()

In [70]:
# There are 593 pages for cars hence when fully scraping, use 1, 594
get_cars(1,3)

Started Page no.1. -  https://www.patpat.lk/vehicle/car?page=1
Started Page no.2. -  https://www.patpat.lk/vehicle/car?page=2

In [77]:
df = pd.DataFrame({'location':locations, 'add_date':add_dates, 'price':prices, 'make':makes, 'model':models,
                  'model_year':model_years, 'gear':gears, 'fuel_type':fuel_types, 
                   'engine_cc':engine_ccs, 'mileage_km':mileage_km})

In [78]:
df.head()

,location,add_date,price,make,model,model_year,gear,fuel_type,engine_cc,mileage_km
0,"For Sale By Madhuranga Gamage on 2020-11-02, M...","For Sale By Madhuranga Gamage on 2020-11-02, M...","1,500,000",Suzuki,Alto,2007,Manual,Petrol,800 CC,67000 km
1,"For Sale By Madhuranga Gamage on 2020-11-02, M...","For Sale By Madhuranga Gamage on 2020-11-02, M...","6,525,000",Toyota,Allion,2013,Automatic,Petrol,1490 CC,87000 km
2,"For Sale By Madhuranga Gamage on 2020-11-02, M...","For Sale By Madhuranga Gamage on 2020-11-02, M...","1,950,000",Toyota,Sprinter,1993,Manual,Petrol,1500 CC,119000 km
3,"For Sale By Madhuranga Gamage on 2020-11-02, M...","For Sale By Madhuranga Gamage on 2020-11-02, M...","2,025,000",Suzuki,Alto,2015,Manual,Petrol,998 CC,76244 km
4,"For Sale By Jayasekaram Ranjan on 2020-11-02, ...","For Sale By Jayasekaram Ranjan on 2020-11-02, ...","3,700,000",Suzuki,Wagon R,2018,Automatic,Petrol,660 CC,56000 km

In [79]:
df['location'] = df['location'].apply(lambda x:x.split(',')[-1].lstrip())
df['add_date'] = df['add_date'].apply(lambda x:x.split(',')[0].split(' ')[-1])

In [80]:
df.head()

,location,add_date,price,make,model,model_year,gear,fuel_type,engine_cc,mileage_km
0,Matara,2020-11-02,"1,500,000",Suzuki,Alto,2007,Manual,Petrol,800 CC,67000 km
1,Matara,2020-11-02,"6,525,000",Toyota,Allion,2013,Automatic,Petrol,1490 CC,87000 km
2,Matara,2020-11-02,"1,950,000",Toyota,Sprinter,1993,Manual,Petrol,1500 CC,119000 km
3,Matara,2020-11-02,"2,025,000",Suzuki,Alto,2015,Manual,Petrol,998 CC,76244 km
4,Maharagama,2020-11-02,"3,700,000",Suzuki,Wagon R,2018,Automatic,Petrol,660 CC,56000 km

In [81]:
df.shape

(20, 10)

In [82]:
# Save the file
df.to_csv('cars_'+str(round(df.shape[0]/10,0))+'_pages.csv', encoding='utf-8', index=False)